# Generated by Django 5.2.10 on 2026-01-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='currency',
            field=models.CharField(default='CDF', max_length=3),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='direction',
            field=models.CharField(choices=[('in', 'Income'), ('out', 'Expense')], default='in', max_length=3),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('offering', 'Offering'), ('tithe', 'Tithe'), ('special_donation', 'Special Donation'), ('project_fund', 'Project Fund'), ('thanksgiving', 'Thanksgiving'), ('construction', 'Construction'), ('donation', 'Donation')], default='offering', max_length=20),
        ),
    ]
