# Generated by Django 5.2.10 on 2026-01-14 07:10

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_default_admin(apps, schema_editor):
    User = apps.get_model('church_management_app', 'User')

    if User.objects.filter(username='admin').exists():
        return

    # Création d'un utilisateur Administrateur (staff) et non superuser
    user = User.objects.create(
        username='admin', 
        email='',
        password=make_password('admin123'),
        is_staff=True,
        is_superuser=False,
        is_active=True,
        role='admin'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0004_financialtransaction_receipts_and_proofs'),
    ]

    operations = [
        migrations.RunPython(create_default_admin, reverse_code=migrations.RunPython.noop),
    ]
