# Generated by Django 5.2.10 on 2026-01-14 07:10

from django.db import migrations


def create_default_admin(apps, schema_editor):
    User = apps.get_model('church_management_app', 'User')

    if User.objects.filter(username='admin').exists():
        return

    try:
        user = User.objects.create_superuser(username='admin', email='', password='admin123')
    except Exception:
        user = User.objects.create(username='admin', email='')
        user.set_password('admin123')
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save()

    try:
        user.role = 'admin'
        user.save(update_fields=['role'])
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0004_financialtransaction_receipts_and_proofs'),
    ]

    operations = [
        migrations.RunPython(create_default_admin, reverse_code=migrations.RunPython.noop),
    ]
