# Generated by Django 5.2.10 on 2026-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0021_baptism_executors_evangelism_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('service', 'Service'), ('meeting', 'Meeting'), ('special', 'Special Event'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('weekly_service', 'Culte hebdomadaire'), ('sunday_service', 'Culte dominical'), ('seminar', 'Séminaire'), ('mothers_teaching', 'Enseignement des mamans'), ('fathers_teaching', 'Enseignement des papas'), ('youth_service', 'Culte des jeunes'), ('department_meeting', 'Rencontre de département'), ('baptism', 'Baptême'), ('evangelism', 'Évangélisation'), ('training', 'Formation'), ('marriage', 'Mariage')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('offering', 'Offrandes'), ('tithe', 'Dîmes'), ('special_donation', 'Don spécial'), ('project_fund', 'Fonds projet'), ('thanksgiving', 'Actions de grâce'), ('construction', 'Construction'), ('donation', 'Don'), ('seed_vow', 'Semences et Vœux'), ('gift_other', 'Dons et autres'), ('functioning', 'Fonctionnement'), ('transport_communication', 'Transport et communication'), ('investment', 'Investissement'), ('rehabilitation', 'Réhabilitation'), ('social_assistance', 'Assistance Sociale')], default='offering', max_length=50),
        ),
    ]
