# Generated by Django 6.0.1 on 2026-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0027_baptismcandidate_address_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='engagement_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id_expiry_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id_issue_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='national_id_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='spiritual_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('pastor', 'Pastor'), ('admin', 'Administrator'), ('administrator', 'Administrator'), ('protocol_head', 'Protocol Head'), ('financial_head', 'Financial Head'), ('logistics_head', 'Logistics Head'), ('evangelism_head', 'Evangelism Head'), ('department_head', 'Department Head'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('member', 'Member'), ('visitor', 'Visitor')], default='visitor', max_length=20),
        ),
    ]
