# Generated by Django 6.0.1 on 2026-01-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0028_remove_member_engagement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
