# Generated by Django 6.0.1 on 2026-01-29 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0029_remove_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchBiography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Biographie de l'église", max_length=200)),
                ('content', models.TextField(help_text="Contenu de la biographie de l'église")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biographies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Biographie de l'église",
                'verbose_name_plural': "Biographies de l'église",
            },
        ),
        migrations.CreateModel(
            name='ChurchConsistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Consistoire de l'église", max_length=200)),
                ('content', models.TextField(help_text='Contenu des informations du consistoire')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Consistoire de l'église",
                'verbose_name_plural': "Consistoires de l'église",
            },
        ),
    ]
