# Generated by Django 6.0.1 on 2026-02-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0030_churchbiography_churchconsistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inactive_reason',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
