# Generated by Django 5.2.10 on 2026-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0038_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='Consolation et Paix Divine', help_text="Nom de l'église", max_length=200)),
                ('church_slogan', models.CharField(blank=True, help_text="Slogan de l'église", max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'application", null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, help_text="Favicon de l'application", null=True, upload_to='settings/')),
                ('address', models.TextField(blank=True, help_text='Adresse complète', null=True)),
                ('city', models.CharField(default='Kinshasa', help_text='Ville', max_length=100)),
                ('country', models.CharField(default='République Démocratique du Congo', help_text='Pays', max_length=100)),
                ('phone_primary', models.CharField(blank=True, help_text='Téléphone principal', max_length=30, null=True)),
                ('phone_secondary', models.CharField(blank=True, help_text='Téléphone secondaire', max_length=30, null=True)),
                ('email_primary', models.EmailField(blank=True, help_text='Email principal', max_length=254, null=True)),
                ('email_secondary', models.EmailField(blank=True, help_text='Email secondaire', max_length=254, null=True)),
                ('office_hours_weekdays', models.CharField(blank=True, help_text='Horaires jours de semaine', max_length=100, null=True)),
                ('office_hours_saturday', models.CharField(blank=True, help_text='Horaires samedi', max_length=100, null=True)),
                ('office_hours_sunday', models.CharField(blank=True, help_text='Horaires dimanche', max_length=100, null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='URL Facebook', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='URL YouTube', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='URL Instagram', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='URL Twitter/X', null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Numéro WhatsApp', max_length=30, null=True)),
                ('telegram_url', models.URLField(blank=True, help_text='URL Telegram', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Paramètre de l'église",
                'verbose_name_plural': "Paramètres de l'église",
            },
        ),
    ]
