# Generated by Django 6.0.4 on 2026-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0039_churchsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/members/'),
        ),
    ]
