# Generated by Django 6.0.4 on 2026-04-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_management_app", "0040_member_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="duration_type",
            field=models.CharField(
                choices=[
                    ("daily", "Journalière"),
                    ("weekly", "Hebdomadaire"),
                    ("21d", "21 jours"),
                    ("40d", "40 jours"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
    ]
