# Generated by Django 6.0.4 on 2026-04-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_management_app", "0041_alter_event_duration_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventattendanceaggregate",
            name="children_total",
            field=models.PositiveIntegerField(default=0, verbose_name="Total enfants"),
        ),
        migrations.AddField(
            model_name="eventattendanceaggregate",
            name="elderly_men",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Hommes âgés (papas/vieillards)"
            ),
        ),
        migrations.AddField(
            model_name="eventattendanceaggregate",
            name="elderly_women",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Femmes âgées (mamas)"
            ),
        ),
        migrations.AddField(
            model_name="eventattendanceaggregate",
            name="grand_total",
            field=models.PositiveIntegerField(default=0, verbose_name="Total général"),
        ),
        migrations.AddField(
            model_name="eventattendanceaggregate",
            name="total_men",
            field=models.PositiveIntegerField(default=0, verbose_name="Total hommes"),
        ),
        migrations.AddField(
            model_name="eventattendanceaggregate",
            name="total_women",
            field=models.PositiveIntegerField(default=0, verbose_name="Total femmes"),
        ),
        migrations.AddField(
            model_name="eventattendanceaggregate",
            name="young_men",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Jeunes hommes (garçons)"
            ),
        ),
        migrations.AddField(
            model_name="eventattendanceaggregate",
            name="young_women",
            field=models.PositiveIntegerField(default=0, verbose_name="Jeunes filles"),
        ),
        migrations.AlterField(
            model_name="eventattendanceaggregate",
            name="female_adults",
            field=models.PositiveIntegerField(default=0, verbose_name="Femmes adultes"),
        ),
        migrations.AlterField(
            model_name="eventattendanceaggregate",
            name="female_children",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Filles (enfants)"
            ),
        ),
        migrations.AlterField(
            model_name="eventattendanceaggregate",
            name="male_adults",
            field=models.PositiveIntegerField(default=0, verbose_name="Hommes adultes"),
        ),
        migrations.AlterField(
            model_name="eventattendanceaggregate",
            name="male_children",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Garçons (enfants)"
            ),
        ),
    ]
