# Generated by Django 6.0.4 on 2026-04-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "church_management_app",
            "0042_eventattendanceaggregate_children_total_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="inactive_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deceased", "Décédé"),
                    ("excluded", "Exclu"),
                    ("resigned", "Démissionné"),
                    ("transferred", "Transféré"),
                    ("absent", "Absent prolongé"),
                    ("other", "Autre"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
