# Generated by Django 6.0.4 on 2026-04-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "church_management_app",
            "0043_alter_member_gender_alter_member_inactive_reason",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catégorie logistique",
                "verbose_name_plural": "Catégories logistiques",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LogisticsCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.SlugField(unique=True)),
                (
                    "display_color",
                    models.CharField(
                        default="secondary",
                        help_text="Couleur du badge (success, warning, danger, info, secondary)",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "État logistique",
                "verbose_name_plural": "États logistiques",
                "ordering": ["name"],
            },
        ),
    ]
