# Generated by Django 6.0.4 on 2026-04-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0044_logisticscategory_logisticscondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'activité", max_length=100)),
                ('description', models.TextField(help_text="Description de l'activité")),
                ('icon', models.CharField(choices=[('bi-book', 'Bible (book)'), ('bi-heart', 'Coeur (heart)'), ('bi-people', 'Gens (people)'), ('bi-music-note-beamed', 'Musique (music)'), ('bi-calendar-event', 'Calendrier (calendar)'), ('bi-hand-thumbs-up', 'Pouce levé (thumbs-up)'), ('bi-star', 'Étoile (star)'), ('bi-lightbulb', 'Idée (lightbulb)'), ('bi-globe', 'Monde (globe)'), ('bi-emoji-smile', 'Sourire (smile)'), ('bi-basket', 'Panier (basket)'), ('bi-tree', 'Arbre (tree)'), ('bi-trophy', 'Trophée (trophy)'), ('bi-camera', 'Caméra (camera)'), ('bi-film', 'Film (film)'), ('bi-controller', 'Manette (controller)'), ('bi-gift', 'Cadeau (gift)'), ('bi-geo-alt', 'Localisation (geo-alt)'), ('bi-house', 'Maison (house)'), ('bi-briefcase', 'Mallette (briefcase)')], default='bi-star', help_text='Icône Bootstrap', max_length=50)),
                ('color', models.CharField(choices=[('primary', 'Bleu (Primary)'), ('success', 'Vert (Success)'), ('warning', 'Jaune (Warning)'), ('danger', 'Rouge (Danger)'), ('info', 'Cyan (Info)'), ('dark', 'Noir (Dark)')], default='primary', help_text="Couleur de l'icône", max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text='Activité visible sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Activité de l'église",
                'verbose_name_plural': "Activités de l'église",
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='activities_section_subtitle',
            field=models.CharField(default='Découvrez ce que nous offrons à notre communauté', help_text='Sous-titre de la section activités', max_length=300),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='activities_section_title',
            field=models.CharField(default='Nos Activités', help_text='Titre de la section activités', max_length=100),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_saturday_desc',
            field=models.CharField(default='Édification de la jeunesse', help_text='Description du culte du samedi', max_length=200),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_saturday_time',
            field=models.CharField(default='Sam 14h00 - 16h00', help_text='Horaire du culte du samedi', max_length=50),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_saturday_title',
            field=models.CharField(default='Réunion Jeunes', help_text='Titre du culte du samedi', max_length=100),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_sunday_desc',
            field=models.CharField(default='Célébration et prédication', help_text='Description du culte du dimanche', max_length=200),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_sunday_time',
            field=models.CharField(default='Dim 9h00 - 12h00', help_text='Horaire du culte du dimanche', max_length=50),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_sunday_title',
            field=models.CharField(default='Culte Dominical', help_text='Titre du culte du dimanche', max_length=100),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_thursday_desc',
            field=models.CharField(default='Moment de communion avec Dieu', help_text='Description du culte du jeudi', max_length=200),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_thursday_time',
            field=models.CharField(default='Jeu 17h00 - 19h00', help_text='Horaire du culte du jeudi', max_length=50),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_thursday_title',
            field=models.CharField(default='Prière et Intercession', help_text='Titre du culte du jeudi', max_length=100),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_tuesday_desc',
            field=models.CharField(default='Approfondissement de la Parole', help_text='Description du culte du mardi', max_length=200),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_tuesday_time',
            field=models.CharField(default='Mar 17h00 - 19h00', help_text='Horaire du culte du mardi', max_length=50),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_tuesday_title',
            field=models.CharField(default='Étude Biblique', help_text='Titre du culte du mardi', max_length=100),
        ),
    ]
