# Generated by Django 6.0.4 on 2026-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0045_churchactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchbiography',
            name='image',
            field=models.ImageField(blank=True, help_text='Image principale de la page À propos', null=True, upload_to='biography/'),
        ),
        migrations.AddField(
            model_name='churchbiography',
            name='mission',
            field=models.TextField(blank=True, help_text='Notre mission', null=True),
        ),
        migrations.AddField(
            model_name='churchbiography',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Sous-titre de la page À propos', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='churchbiography',
            name='valeurs',
            field=models.TextField(blank=True, help_text='Nos valeurs', null=True),
        ),
        migrations.AddField(
            model_name='churchbiography',
            name='vision',
            field=models.TextField(blank=True, help_text='Notre vision', null=True),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='cta_button_text',
            field=models.CharField(default='Nous Contacter', help_text='Texte du bouton CTA', max_length=50),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='cta_subtitle',
            field=models.TextField(blank=True, default="Que vous soyez nouveau dans la foi ou à la recherche d'une famille spirituelle, vous êtes le bienvenu parmi nous.", help_text='Sous-titre/description de la section CTA', null=True),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='cta_title',
            field=models.CharField(default='Rejoignez notre communauté', help_text='Titre de la section CTA', max_length=200),
        ),
        migrations.AlterField(
            model_name='churchbiography',
            name='content',
            field=models.TextField(help_text="Contenu de la biographie de l'église (supporte le HTML)"),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='church_slogan',
            field=models.TextField(blank=True, help_text="Slogan de l'église (supporte le HTML)", null=True),
        ),
    ]
