# Generated by Django 6.0.4 on 2026-04-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0046_churchbiography_image_churchbiography_mission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du culte (ex: Culte Dominical)', max_length=100)),
                ('day', models.CharField(choices=[('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], default='Dimanche', help_text='Jour de la semaine', max_length=20)),
                ('time', models.CharField(help_text='Horaire (ex: 9h00 - 12h00)', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Description courte (ex: Célébration et prédication)', max_length=200, null=True)),
                ('color', models.CharField(choices=[('primary', 'Bleu (Primary)'), ('success', 'Vert (Success)'), ('warning', 'Jaune (Warning)'), ('danger', 'Rouge (Danger)'), ('info', 'Cyan (Info)'), ('dark', 'Noir (Dark)'), ('secondary', 'Gris (Secondary)'), ('light', 'Blanc (Light)')], default='primary', help_text='Couleur de fond', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text='Culte visible sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horaire de culte',
                'verbose_name_plural': 'Horaires des cultes',
                'ordering': ['order', 'day', 'time'],
            },
        ),
    ]
