# Generated by Django 6.0.4 on 2026-04-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0047_churchservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsettings',
            name='activities_section_subtitle',
            field=models.CharField(blank=True, default='Découvrez ce que nous offrons à notre communauté', help_text='Sous-titre de la section activités', max_length=300),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='activities_section_title',
            field=models.CharField(blank=True, default='Nos Activités', help_text='Titre de la section activités', max_length=100),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='church_name',
            field=models.CharField(blank=True, default='Consolation et Paix Divine', help_text="Nom de l'église", max_length=200),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='city',
            field=models.CharField(blank=True, default='Kinshasa', help_text='Ville', max_length=100),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='country',
            field=models.CharField(blank=True, default='République Démocratique du Congo', help_text='Pays', max_length=100),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Nous Contacter', help_text='Texte du bouton CTA', max_length=50),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='cta_title',
            field=models.CharField(blank=True, default='Rejoignez notre communauté', help_text='Titre de la section CTA', max_length=200),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_saturday_desc',
            field=models.CharField(blank=True, default='Édification de la jeunesse', help_text='Description du culte du samedi', max_length=200),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_saturday_time',
            field=models.CharField(blank=True, default='Sam 14h00 - 16h00', help_text='Horaire du culte du samedi', max_length=50),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_saturday_title',
            field=models.CharField(blank=True, default='Réunion Jeunes', help_text='Titre du culte du samedi', max_length=100),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_sunday_desc',
            field=models.CharField(blank=True, default='Célébration et prédication', help_text='Description du culte du dimanche', max_length=200),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_sunday_time',
            field=models.CharField(blank=True, default='Dim 9h00 - 12h00', help_text='Horaire du culte du dimanche', max_length=50),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_sunday_title',
            field=models.CharField(blank=True, default='Culte Dominical', help_text='Titre du culte du dimanche', max_length=100),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_thursday_desc',
            field=models.CharField(blank=True, default='Moment de communion avec Dieu', help_text='Description du culte du jeudi', max_length=200),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_thursday_time',
            field=models.CharField(blank=True, default='Jeu 17h00 - 19h00', help_text='Horaire du culte du jeudi', max_length=50),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_thursday_title',
            field=models.CharField(blank=True, default='Prière et Intercession', help_text='Titre du culte du jeudi', max_length=100),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_tuesday_desc',
            field=models.CharField(blank=True, default='Approfondissement de la Parole', help_text='Description du culte du mardi', max_length=200),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_tuesday_time',
            field=models.CharField(blank=True, default='Mar 17h00 - 19h00', help_text='Horaire du culte du mardi', max_length=50),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='service_tuesday_title',
            field=models.CharField(blank=True, default='Étude Biblique', help_text='Titre du culte du mardi', max_length=100),
        ),
    ]
