# Generated by Django 6.0.4 on 2026-05-09 00:30

from django.db import migrations, models


def forwards_convert_administrator_role(apps, schema_editor):
    User = apps.get_model('church_management_app', 'User')
    User.objects.filter(role='administrator').update(role='admin')


def backwards_noop(apps, schema_editor):
    # Pas de rollback automatique
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0049_user_permission_profile'),
    ]

    operations = [
        migrations.RunPython(forwards_convert_administrator_role, backwards_noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('pastor', 'Pastor'), ('admin', 'Administrator'), ('protocol_head', 'Protocol Head'), ('financial_head', 'Financial Head'), ('logistics_head', 'Logistics Head'), ('evangelism_head', 'Evangelism Head'), ('department_head', 'Department Head'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('member', 'Member'), ('visitor', 'Visitor')], default='visitor', max_length=20),
        ),
    ]
