# Generated by Django 6.0.4 on 2026-05-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_management_app', '0005_create_default_admin'),
        ('church_management_app', '0050_remove_administrator_role'),
    ]

    operations = [
    ]
